/**
* MG M2 Lightning API
* Magento 2.3 API as standalone server
*
* OpenAPI spec version: 0.1.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * Error_parameters.h
 *
 * Error parameters list
 */

#ifndef Error_parameters_H_
#define Error_parameters_H_


#include "ModelBase.h"

#include "Error-parameters-item.h"
#include <vector>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// Error parameters list
/// </summary>
class  Error_parameters
    : public ModelBase
{
public:
    Error_parameters();
    virtual ~Error_parameters();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Error_parameters members


protected:
};

}
}
}
}

#endif /* Error_parameters_H_ */
