/**
* MG M2 Lightning API
* Magento 2.3 API as standalone server
*
* OpenAPI spec version: 0.1.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * Error_parameters_item.h
 *
 * Error parameters item
 */

#ifndef Error_parameters_item_H_
#define Error_parameters_item_H_


#include "ModelBase.h"

#include <string>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// Error parameters item
/// </summary>
class  Error_parameters_item
    : public ModelBase
{
public:
    Error_parameters_item();
    virtual ~Error_parameters_item();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Error_parameters_item members

    /// <summary>
    /// ACL resource
    /// </summary>
    std::string getResources() const;
    void setResources(std::string value);
    bool resourcesIsSet() const;
    void unsetResources();
    /// <summary>
    /// Missing or invalid field name
    /// </summary>
    std::string getFieldName() const;
    void setFieldName(std::string value);
    bool fieldNameIsSet() const;
    void unsetFieldName();
    /// <summary>
    /// Incorrect field value
    /// </summary>
    std::string getFieldValue() const;
    void setFieldValue(std::string value);
    bool fieldValueIsSet() const;
    void unsetFieldValue();

protected:
    std::string m_Resources;
    bool m_ResourcesIsSet;
    std::string m_FieldName;
    bool m_FieldNameIsSet;
    std::string m_FieldValue;
    bool m_FieldValueIsSet;
};

}
}
}
}

#endif /* Error_parameters_item_H_ */
