/**
* MG M2 Lightning API
* Magento 2.3 API as standalone server
*
* OpenAPI spec version: 0.1.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * Error_errors.h
 *
 * Errors list
 */

#ifndef Error_errors_H_
#define Error_errors_H_


#include "ModelBase.h"

#include "Error-errors-item.h"
#include <vector>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// Errors list
/// </summary>
class  Error_errors
    : public ModelBase
{
public:
    Error_errors();
    virtual ~Error_errors();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Error_errors members


protected:
};

}
}
}
}

#endif /* Error_errors_H_ */
