/**
* MG M2 Lightning API
* Magento 2.3 API as standalone server
*
* OpenAPI spec version: 0.1.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "Error-parameters.h"

namespace io {
namespace swagger {
namespace server {
namespace model {

Error_parameters::Error_parameters()
{
    
}

Error_parameters::~Error_parameters()
{
}

void Error_parameters::validate()
{
    // TODO: implement validation
}

nlohmann::json Error_parameters::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void Error_parameters::fromJson(nlohmann::json& val)
{
    
}



}
}
}
}

