/**
* MG M2 Lightning API
* Magento 2.3 API as standalone server
*
* OpenAPI spec version: 0.1.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * V1IntegrationAdminTokenPostBody.h
 *
 *
 */

#ifndef V1IntegrationAdminTokenPostBody_H_
#define V1IntegrationAdminTokenPostBody_H_


#include "ModelBase.h"

#include <string>

namespace io::swagger::server::model {

/// <summary>
///
/// </summary>
    class V1IntegrationAdminTokenPostBody
            : public ModelBase {
    public:
        V1IntegrationAdminTokenPostBody();

        virtual ~V1IntegrationAdminTokenPostBody();

        /////////////////////////////////////////////
        /// ModelBase overrides

        void validate() override;

        nlohmann::json toJson() const override;

        void fromJson(nlohmann::json &json) override;

        /////////////////////////////////////////////
        /// V1IntegrationAdminTokenPostBody members

        /// <summary>
        ///
        /// </summary>
        std::string getUsername() const;

        void setUsername(std::string value);

        /// <summary>
        ///
        /// </summary>
        std::string getPassword() const;

        void setPassword(std::string value);

    protected:
        std::string m_Username;

        std::string m_Password;

    };

}

#endif /* V1IntegrationAdminTokenPostBody_H_ */
