version: '3'

services:
  gdbserver:
    build: .
    security_opt: # options needed for gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    container_name: cpp-debug
    network_mode: bridge
    ports:
      - "7722:22"
      - "7777:7777"
      - "8080:8080"
#    volumes:
#      - .:/code

networks:
  default:
    external:
      name: bridge