/**
* MG M2 Lightning API
* Magento 2.3 API as standalone server
*
* OpenAPI spec version: 0.1.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

/*
* IntegrationadmintokenApiImpl.h
*
* 
*/

#ifndef INTEGRATIONADMINTOKEN_API_IMPL_H_
#define INTEGRATIONADMINTOKEN_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <IntegrationadmintokenApi.h>

#include "Error-response.h"
#include "V1IntegrationAdminTokenPostBody.h"
#include <string>

namespace io::swagger::server::api {

    using namespace io::swagger::server::model;

    class IntegrationadmintokenApiImpl : public io::swagger::server::api::IntegrationadmintokenApi {
    public:
        IntegrationadmintokenApiImpl(Pistache::Address addr);
//    IntegrationadmintokenApiImpl(Pistache::Address addr)
//            : IntegrationadmintokenApi(addr)
//    {
//    }
//    ~IntegrationadmintokenApiImpl() { };

        void V1_integration_admin_token_post(const V1IntegrationAdminTokenPostBody &v1IntegrationAdminTokenPostBody,
                                             Pistache::Http::ResponseWriter &response);

    };

}


#endif