/**
* MG M2 Lightning API
* Magento 2.3 API as standalone server
*
* OpenAPI spec version: 0.1.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

#include "IntegrationadmintokenApiImpl.h"

namespace io {
namespace swagger {
namespace server {
namespace api {

using namespace io::swagger::server::model;

IntegrationadmintokenApiImpl::IntegrationadmintokenApiImpl(Pistache::Address addr)
    : IntegrationadmintokenApi(addr)
    {
    }

void IntegrationadmintokenApiImpl::V1_integration_admin_token_post(const V1IntegrationAdminTokenPostBody &v1IntegrationAdminTokenPostBody, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}
}
}

