/**
* MG M2 Lightning API
* Magento 2.3 API as standalone server
*
* OpenAPI spec version: 0.1.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * IntegrationadmintokenApi.h
 *
 * 
 */

#ifndef IntegrationadmintokenApi_H_
#define IntegrationadmintokenApi_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include "Error-response.h"
#include "V1IntegrationAdminTokenPostBody.h"
#include <string>

namespace io {
namespace swagger {
namespace server {
namespace api {

using namespace io::swagger::server::model;

class  IntegrationadmintokenApi {
public:
    IntegrationadmintokenApi(Pistache::Address addr);
    virtual ~IntegrationadmintokenApi() {};
    void init(size_t thr);
    void start();
    void shutdown();

    const std::string base = "/v1";

private:
    void setupRoutes();

    void V1_integration_admin_token_post_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void integrationadmintoken_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    std::shared_ptr<Pistache::Http::Endpoint> httpEndpoint;
    Pistache::Rest::Router router;


    /// <summary>
    /// integration/admin/token
    /// </summary>
    /// <remarks>
    /// Create access token for admin given the admin credentials.
    /// </remarks>
    /// <param name="v1IntegrationAdminTokenPostBody"> (optional)</param>
    virtual void V1_integration_admin_token_post(const V1IntegrationAdminTokenPostBody &v1IntegrationAdminTokenPostBody, Pistache::Http::ResponseWriter &response) = 0;

};

}
}
}
}

#endif /* IntegrationadmintokenApi_H_ */

